### ISSUE TITLE
The initial generation of a key ends with FileNotFoundError

### ISSUE THREAD

**Issue by hpk42** [fschulze/certsling#3]
more specifically:

```
letsencrypt-remote -r -s pytest.org doc.ptyest.org www.pytest.org docs.pytest.org 
Using existing private user key 'user.key'.
Using existing public user key 'user.pub'.
Using existing key 'pytest.org/pytest.org.key'.
Generating csr 'pytest.org/pytest.org-20161107.csr'.
Traceback (most recent call last):
  File "/home/hpk/.local/bin/letsencrypt-remote", line 11, in <module>
    sys.exit(main())
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/letsencrypt_remote.py", line 730, in main
    generate(base, domains, challenges, regenerate, ca)
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/letsencrypt_remote.py", line 693, in generate
    csr = date_gen('csr', '.csr', gencsr, key, domains)
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/letsencrypt_remote.py", line 118, in generator
    generate(fn_date, *args, **kw)
  File "/home/hpk/.local/venvs/letsencrypt-remote/lib/python3.5/site-packages/letsencrypt_remote.py", line 144, in gencsr
    with OPENSSL_CONF.open('rb') as f:
  File "/usr/lib/python3.5/pathlib.py", line 1151, in open
    opener=self._opener)
  File "/usr/lib/python3.5/pathlib.py", line 1005, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.5/pathlib.py", line 371, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/etc/openssl/openssl.cnf'
```

**Comment by hpk42** [comment]
i suspect checking if `/etc/ssl/openssl.cnf` exists and if not looking for `/usr/local/...` would already go a long way.

**Comment by fschulze** [comment]
This should be fixed on master.

**Comment by hpk42** [comment]
it works, thanks.
